# Generated by Django 3.0.11 on 2021-01-04 13:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='back_text',
            field=ckeditor.fields.RichTextField(help_text='Usually the Answer', max_length=2000, verbose_name='Backside Text'),
        ),
    ]
