# Generated by Django 3.0.11 on 2021-01-05 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0002_auto_20210104_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='card',
            field=models.ForeignKey(help_text='Card of the performance', on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='flashcards.Card'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='owner',
            field=models.ForeignKey(help_text='User of the card performance', on_delete=django.db.models.deletion.CASCADE, related_name='performances', to=settings.AUTH_USER_MODEL),
        ),
    ]
