# Generated by Django 3.0.11 on 2021-01-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_auto_20210105_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', help_text='Priority of the card to learn', max_length=20, verbose_name='Learning Priority'),
        ),
    ]
