# Generated by Django 3.0.11 on 2021-08-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_auto_20210111_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='good_one',
            field=models.BooleanField(default=True),
        ),
    ]
