# Generated by Django 3.0.11 on 2021-05-04 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shareholder', '0002_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='collaborator',
            field=models.ForeignKey(help_text='Assignment Collaborator', limit_choices_to={'groups__name': 'Shareholder'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='notes',
            field=models.TextField(default='Project Lead', help_text='Information of the collaborators role and responsibilities', max_length=1000, verbose_name='Assignment Notes'),
        ),
    ]
