# Generated by Django 3.0.11 on 2021-05-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0004_auto_20210504_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='notes',
            field=models.TextField(default='Task Lead', help_text='Information of the collaborators role and responsibilities', max_length=1000, verbose_name='Assignment Notes'),
        ),
        migrations.AlterField(
            model_name='task',
            name='feature_branch',
            field=models.CharField(blank=True, max_length=255, verbose_name='GIT feature branch name'),
        ),
    ]
