# Generated by Django 3.0.11 on 2021-05-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0006_auto_20210506_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='report_file',
            field=models.FileField(blank=True, help_text="File upload for report of the task's fulfillment.", null=True, upload_to='shareholder/task/reports/', verbose_name='Report File'),
        ),
        migrations.AddField(
            model_name='task',
            name='report_text',
            field=models.TextField(blank=True, help_text="Report of the task's fulfillment.", max_length=5000, null=True, verbose_name='Report'),
        ),
    ]
