# Generated by Django 3.0.11 on 2021-05-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0007_auto_20210506_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='workload',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Workload shares'),
        ),
    ]
