# Generated by Django 3.0.11 on 2021-05-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0008_auto_20210506_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('proposed', 'Task is proposed'), ('active', 'Task is active'), ('working', 'Task is being build'), ('review', 'Task is under review'), ('completed', 'Task is completed'), ('failed', 'Task is failed')], default='proposed', help_text='Status of the task', max_length=20, verbose_name='Status'),
        ),
    ]
