# Generated by Django 3.0.11 on 2021-05-10 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shareholder', '0009_auto_20210506_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('year', models.PositiveSmallIntegerField(default=2021, help_text='The year the surplus was generated', verbose_name='Year')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'Juli'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='The month the surplus was generated', verbose_name='Month')),
                ('surplus_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Surplus €')),
                ('total_shares', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Shares at reporting time')),
            ],
            options={
                'verbose_name': 'Income Period',
                'verbose_name_plural': 'Income Periods',
                'ordering': ('-year', '-month'),
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Dividends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('task_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Share Hours for Tasks')),
                ('review_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Share Hours for Reviews')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Dividend Amount €')),
                ('income_period', models.ForeignKey(help_text='Income Period the dividend relates to', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='shareholder.IncomePeriod')),
                ('shareholder', models.ForeignKey(help_text='Shareholder receiving the dividends', limit_choices_to={'groups__name': 'Shareholder'}, on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dividends',
                'verbose_name_plural': 'Dividends',
                'ordering': ('-income_period', '-shareholder'),
                'unique_together': {('shareholder', 'income_period')},
            },
        ),
    ]
