# Generated by Django 3.0.11 on 2020-12-20 08:00

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('topic', models.CharField(help_text='Topic of Memo Card', max_length=255, verbose_name='Topic')),
                ('is_template', models.BooleanField(default=False, help_text='This set can be forked by other users', verbose_name='Template')),
                ('owner', models.ForeignKey(blank=True, help_text='Memo Set is owned by this user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memosets', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent Memo Set', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='memorizer.MemoSet')),
            ],
            options={
                'verbose_name': 'Set',
                'verbose_name_plural': 'Sets',
                'unique_together': {('owner', 'parent', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='MemoCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('topic', models.CharField(help_text='Topic of Memo Card', max_length=255, verbose_name='Topic')),
                ('question_text', models.TextField(max_length=2000, verbose_name='Question (Text)')),
                ('answer_text', models.TextField(max_length=2000, verbose_name='Answer (Text)')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Memorization Data')),
                ('score', models.DecimalField(decimal_places=1, default=0.0, help_text='Memo Card is assigned to this set', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Memorization Score')),
                ('memoset', models.ForeignKey(help_text='Memo Card is assigned to this set', on_delete=django.db.models.deletion.CASCADE, related_name='memocards', to='memorizer.MemoSet')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
