# Generated by Django 3.0.11 on 2020-12-20 08:22

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memocard',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Memorization Data'),
        ),
    ]
