# Generated by Django 3.0.11 on 2020-12-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorizer', '0002_auto_20201220_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoset',
            name='depth',
            field=models.PositiveIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoset',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoset',
            name='rgt',
            field=models.PositiveIntegerField(db_index=True, default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoset',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
