# Generated by Django 3.0.11 on 2020-12-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorizer', '0003_auto_20201221_0856'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memoset',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='memoset',
            name='parent',
        ),
    ]
