# Generated by Django 3.0.11 on 2020-12-31 07:18

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(help_text='Name of the group', max_length=255, verbose_name='Group Title')),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL part of the study group', max_length=255, verbose_name='Group Slug')),
                ('description', ckeditor.fields.RichTextField(max_length=2000, verbose_name='Description of Study Group')),
                ('is_main_user_group', models.BooleanField(default=False, help_text='If this is the main user group', verbose_name='Main User Group')),
                ('join_mode', models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Managed'), (2, 'Private')], default=2, help_text='How new members can join', verbose_name='Join Group Mode')),
                ('new_member_role', models.PositiveSmallIntegerField(choices=[(0, 'Viewer'), (1, 'Editor'), (2, 'Admin')], default=0, help_text='Default role of new member', verbose_name='Default member role')),
            ],
            options={
                'verbose_name': 'Study Group',
                'verbose_name_plural': 'Study Groups',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'Viewer'), (1, 'Editor'), (2, 'Admin')], default=0, help_text="Member's role in study group", verbose_name='Role')),
                ('group', models.ForeignKey(help_text='Study Group of the relation', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='studygroups.StudyGroup')),
                ('member', models.ForeignKey(help_text='User of the relation', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
            },
        ),
    ]
