# Generated by Django 3.0.11 on 2020-12-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URL part of the study group', unique=True, verbose_name='Group Slug'),
        ),
    ]
