# Generated by Django 3.0.11 on 2020-12-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0002_auto_20201231_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='approved',
            field=models.BooleanField(default=False, help_text='Membership is approved', verbose_name='Approved'),
        ),
    ]
