# Generated by Django 3.0.11 on 2020-12-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0003_membership_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studygroup',
            options={'ordering': ('-is_main_user_group',), 'verbose_name': 'Study Group', 'verbose_name_plural': 'Study Groups'},
        ),
        migrations.AddField(
            model_name='studygroup',
            name='is_publicly_available',
            field=models.BooleanField(default=True, help_text='Study Group can be found in the directory', verbose_name='Publicly available'),
        ),
    ]
