# Generated by Django 3.0.11 on 2020-12-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0006_auto_20201231_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')], default='viewer', help_text="Member's role in study group", max_length=20, verbose_name='Role'),
        ),
    ]
