# Generated by Django 3.0.11 on 2021-01-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0008_auto_20201231_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='blocked',
            field=models.BooleanField(default=False, help_text='Membership is blocked', verbose_name='Blocked'),
        ),
    ]
