# Generated by Django 3.0.11 on 2021-01-02 05:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studygroups', '0009_membership_blocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('role', 'member'), 'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('group', 'member')},
        ),
    ]
