# Generated by Django 3.0.11 on 2020-12-21 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardset', '0002_auto_20201221_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoset',
            name='owner',
            field=models.ForeignKey(help_text='Memo Set is owned by this user', on_delete=django.db.models.deletion.CASCADE, related_name='memosets', to=settings.AUTH_USER_MODEL),
        ),
    ]
