# Generated by Django 3.0.11 on 2020-12-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardset', '0003_auto_20201221_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoset',
            name='topic',
            field=models.CharField(help_text='Topic of Memo Set', max_length=255, verbose_name='Topic'),
        ),
    ]
