# Generated by Django 3.0.11 on 2020-12-23 09:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardset', '0004_auto_20201222_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memocard',
            name='data',
        ),
        migrations.RemoveField(
            model_name='memocard',
            name='score',
        ),
        migrations.CreateModel(
            name='MemoCardStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('data', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Memorization Data')),
                ('score', models.DecimalField(decimal_places=1, default=0.0, help_text='Memorization Score of the Memo Card', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Memorization Score')),
                ('card', models.ForeignKey(help_text='Card of the performance', on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='cardset.MemoCard')),
                ('owner', models.ForeignKey(help_text='User of the card performance', on_delete=django.db.models.deletion.CASCADE, related_name='performances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card Performance',
                'verbose_name_plural': 'Card Performances',
            },
        ),
    ]
