# Generated by Django 3.0.11 on 2020-12-25 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardset', '0007_auto_20201223_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memocard',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='Memo Set is created by this user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memocards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memocardperformance',
            name='data',
            field=jsonfield.fields.JSONField(default={'learning': [], 'recalling': []}, verbose_name='Memorization Data'),
        ),
        migrations.AlterUniqueTogether(
            name='memocardperformance',
            unique_together={('owner', 'memocard')},
        ),
    ]
