# Generated by Django 3.0.11 on 2020-12-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardset', '0009_auto_20201225_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memocardperformance',
            name='learning_timeout',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Learning Timeout in seconds'),
        ),
    ]
