# Generated by Django 3.0.11 on 2020-12-26 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardset', '0011_auto_20201226_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memocardperformance',
            name='test_score',
        ),
        migrations.RemoveField(
            model_name='memocardperformance',
            name='test_total_time',
        ),
        migrations.RemoveField(
            model_name='memocardperformance',
            name='train_score',
        ),
        migrations.RemoveField(
            model_name='memocardperformance',
            name='train_total_time',
        ),
        migrations.AddField(
            model_name='memocardperformance',
            name='learn_score',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Learn Score of the Memo Card for the User', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Learn Score'),
        ),
        migrations.AddField(
            model_name='memocardperformance',
            name='learn_total_time',
            field=models.PositiveIntegerField(default=0, help_text='Total time spend on learning', verbose_name='Total Learn Time'),
        ),
        migrations.AddField(
            model_name='memocardperformance',
            name='learn_trials',
            field=models.PositiveIntegerField(default=0, help_text='Total learnings tried', verbose_name='Total Learn Trials'),
        ),
        migrations.AddField(
            model_name='memocardperformance',
            name='recall_score',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Recall Score of the Memo Card for the User', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Recall Score'),
        ),
        migrations.AddField(
            model_name='memocardperformance',
            name='recall_total_time',
            field=models.PositiveIntegerField(default=0, help_text='Total time spend on testing', verbose_name='Total Recall Time'),
        ),
        migrations.AddField(
            model_name='memocardperformance',
            name='recall_trials',
            field=models.PositiveIntegerField(default=0, help_text='Total recalls tried', verbose_name='Total Recall Trials'),
        ),
    ]
