# Generated by Django 3.0.11 on 2020-12-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardset', '0012_auto_20201226_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memocardperformance',
            name='learning_timeout',
            field=models.PositiveSmallIntegerField(default=120, help_text='Learning Timeout in seconds', verbose_name='Learning Timeout'),
        ),
    ]
