# Generated by Django 3.0.11 on 2020-12-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardset', '0013_auto_20201229_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='memocardperformance',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='Learning of associated card is paused.', verbose_name='Paused'),
        ),
        migrations.AddField(
            model_name='memocardperformance',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], default=1, verbose_name='Learning Priority'),
        ),
        migrations.AlterField(
            model_name='memocard',
            name='topic',
            field=models.CharField(blank=True, help_text='Topic of Memo Card', max_length=255, null=True, verbose_name='Topic'),
        ),
    ]
