# Generated by Django 3.0.11 on 2020-12-29 09:30

from django.db import migrations, models
import uuid

#
# See for migrations 15,16,17
# https://docs.djangoproject.com/en/3.0/howto/writing-migrations/#migrations-that-add-unique-fields

class Migration(migrations.Migration):

    dependencies = [
        ('cardset', '0014_auto_20201229_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='memocardperformance',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
