# Generated by Django 3.0.11 on 2020-12-29 09:36

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('cardset', 'memocardperformance')
    for row in MyModel.objects.all():
        row.unique_id = uuid.uuid4()
        row.save(update_fields=['unique_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('cardset', '0015_memocardperformance_unique_id'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
