# Generated by Django 3.0.11 on 2020-12-29 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cardset', '0016_auto_20201229_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memocardperformance',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
