# Generated by Django 3.0.11 on 2020-12-31 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0002_auto_20201231_0826'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardset', '0018_auto_20201230_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoset',
            name='studygroup',
            field=models.ForeignKey(blank=True, help_text='Belongs to study group.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardsets', to='studygroups.StudyGroup'),
        ),
        migrations.AlterField(
            model_name='memocard',
            name='creator',
            field=models.ForeignKey(help_text='Memo Set is created by this user', on_delete=django.db.models.deletion.CASCADE, related_name='memocards', to=settings.AUTH_USER_MODEL),
        ),
    ]
